# Site settings
author: Ting Chung
title: Creating my adopt pet CLI
header-img: img/home-bg.png
email: tchung682@gmail.com
copyright_name: Ting Chung
description: > # this means to ignore newlines until "baseurl:"
  My journey with adopt pet CLI
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ting682

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
